"""
Per-axis ablations for the paper's Section IV-F comparisons "fixed vs dynamic
interests" and "fixed vs adaptive interaction mode": the real DecisionEngine
with ONE lesson axis pinned to the static baseline's default arm (theme ->
dino, modality -> tap), everything else — Thompson sampling on the other
axes, stopping rule, safety layer, interventions — untouched.

Same population, seed and horizon as the simulation study (N=80,
EVAL_SEED=42, 40 activities), so full_aura here reproduces AURA there.

    backend/.venv/bin/python -m research.run_axis_ablation

Writes research/results/axis_ablation.csv and axis_ablation.md.
"""
import csv
import statistics
from pathlib import Path

from scipy import stats

import research  # noqa: F401 — sys.path bootstrap
from research.ablations import ABLATION_ENGINES
from research.baselines.static import DEFAULT_ARMS
from research.harness import run_aura_condition
from research.metrics import summarize
from research.run_learning_outcomes import outcomes
from research.run_simulation_study import EVAL_SEED, N_ACTIVITIES, N_EVAL
from research.simulator.child import generate_population

from app.engine.decision_engine import DecisionEngine
from app.engine.experiment_manager import ArmChoice

RESULTS = Path(__file__).parent / "results"


def pinned_engine(axis_code: str) -> type[DecisionEngine]:
    class PinnedAxisEngine(DecisionEngine):
        def choose_arm(self, child_id, axis, distress_level, outcome_kind: str = "immediate") -> ArmChoice:
            if axis.code != axis_code:
                return super().choose_arm(child_id, axis, distress_level, outcome_kind=outcome_kind)
            arms = self.experiments.arms_for(axis.id)
            arm = next(a for a in arms if a.code == DEFAULT_ARMS[axis_code])
            return ArmChoice(
                axis_id=axis.id, axis_code=axis.code, arm_id=arm.id, arm_code=arm.code,
                decision_type="locked", reason=f"ablation: {axis_code} pinned", candidate_arm_ids=[arm.id],
            )

    return PinnedAxisEngine


CONDITIONS = {
    "full_aura": ABLATION_ENGINES["full_aura"],
    "fixed_interest_theme": pinned_engine("theme"),
    "fixed_interaction_mode": pinned_engine("modality"),
}
METRICS = ["cumulative_regret", "retention_7d_percent", "distress_events", "accuracy", "learning_gain", "completion_rate"]


def main() -> None:
    rows = []
    for child in generate_population(N_EVAL, seed=EVAL_SEED):
        truth = {"teaching_method": child.true_best_method, "modality": child.true_best_modality, "theme": child.true_best_theme}
        seed = EVAL_SEED * 1000 + child.child_index
        for name, engine_cls in CONDITIONS.items():
            log, db, child_id, topic = run_aura_condition(
                child.clone_for_condition(seed), condition_name=name, engine_cls=engine_cls, n_activities=N_ACTIVITIES, seed=seed
            )
            summary = summarize(log, db, child_id, topic, truth)
            rows.append({"condition": name, "child_index": child.child_index,
                         **{k: summary[k] for k in ("cumulative_regret", "retention_7d_percent", "distress_events")}, **outcomes(log)})

    RESULTS.mkdir(exist_ok=True)
    with open(RESULTS / "axis_ablation.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    by = {c: {r["child_index"]: r for r in rows if r["condition"] == c} for c in CONDITIONS}
    ids = sorted(by["full_aura"])
    lines = [
        "# Per-axis ablation: fixed vs adaptive interest theme and interaction mode (Section IV-F)",
        "",
        f"Mechanically generated by `research/run_axis_ablation.py` — N={N_EVAL}, {N_ACTIVITIES} activities, EVAL_SEED={EVAL_SEED}. "
        f"Pinned arms = the static baseline's defaults ({DEFAULT_ARMS}).",
        "",
        "| Condition | " + " | ".join(METRICS) + " |",
        "|---|" + "---|" * len(METRICS),
    ]
    for c in CONDITIONS:
        lines.append(f"| {c} | " + " | ".join(f"{statistics.mean(by[c][i][m] for i in ids):.3f}" for m in METRICS) + " |")
    lines += ["", "## Paired t-tests vs full_aura (Holm-adjusted across the 2 ablations, per metric)", "",
              "| Metric | Ablation | mean diff (ablation − full) | Cohen's d_z | t-test p | Holm-adjusted |", "|---|---|---|---|---|---|"]
    for m in METRICS:
        tests = []
        for c in CONDITIONS:
            if c == "full_aura":
                continue
            diffs = [by[c][i][m] - by["full_aura"][i][m] for i in ids]
            sd = statistics.stdev(diffs)
            p = stats.ttest_rel([by[c][i][m] for i in ids], [by["full_aura"][i][m] for i in ids]).pvalue if sd > 0 else 1.0
            tests.append([c, statistics.mean(diffs), statistics.mean(diffs) / sd if sd > 0 else float("nan"), p])
        order = sorted(range(len(tests)), key=lambda i: tests[i][3])
        running = 0.0
        for rank, i in enumerate(order):
            running = max(running, min(1.0, tests[i][3] * (len(tests) - rank)))
            tests[i].append(running)
        for c, diff, dz, p, adj in tests:
            lines.append(f"| {m} | {c} | {diff:+.3f} | {dz:+.2f} | {p:.4f} | {adj:.4f}{' **significant**' if adj < 0.05 else ''} |")
    (RESULTS / "axis_ablation.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
