"""
Learning-outcome metrics per condition for the paper's Section IV-B/IV-F —
learning accuracy, learning gain and completion rate — on exactly the
simulation study's setup (same calibration, same runners, same N=80
population and EVAL_SEED=42), so these numbers sit beside regret/retention
in simulation_summary.md without any change in what was run.

    backend/.venv/bin/python -m research.run_learning_outcomes

Writes research/results/learning_outcomes.csv and learning_outcomes.md.
"""
import csv
import statistics
from pathlib import Path

from scipy import stats

import research  # noqa: F401 — sys.path bootstrap
from research.run_simulation_study import (
    EVAL_SEED,
    N_EVAL,
    build_condition_runners,
    calibrate_correlational_lookup,
    calibrate_population_best,
)
from research.simulator.child import generate_population

RESULTS = Path(__file__).parent / "results"
WINDOW = 10  # activities at each end of the run for the gain comparison


def outcomes(log) -> dict:
    lessons = [t for t in log.trials if not t.is_intervention]
    answered = [t for t in lessons if t.correct is not None]
    n_act = max(t.activity_index for t in log.trials) + 1
    early = [t for t in answered if t.activity_index < WINDOW]
    late = [t for t in answered if t.activity_index >= n_act - WINDOW]
    lesson_acts = {t.activity_index for t in lessons}
    abandoned_acts = {t.activity_index for t in lessons if t.abandoned}
    acc = lambda ts: sum(t.correct for t in ts) / len(ts) if ts else float("nan")
    return {
        "accuracy": acc(answered),
        "accuracy_first10": acc(early),
        "accuracy_last10": acc(late),
        "learning_gain": acc(late) - acc(early),
        "completion_rate": 1 - len(abandoned_acts) / len(lesson_acts),
        "final_mastery": next((t.mastery_after for t in reversed(lessons) if t.mastery_after is not None), float("nan")),
    }


def main() -> None:
    population_best = calibrate_population_best()
    corr_lookup, low_cut, high_cut = calibrate_correlational_lookup()
    runners = build_condition_runners(population_best, corr_lookup, (low_cut, high_cut))
    rows = []
    for child in generate_population(N_EVAL, seed=EVAL_SEED):
        for name, runner in runners.items():
            log, *_ = runner(child, EVAL_SEED * 1000 + child.child_index)
            rows.append({"condition": name, "child_index": child.child_index, **outcomes(log)})

    RESULTS.mkdir(exist_ok=True)
    with open(RESULTS / "learning_outcomes.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    metrics = ["accuracy", "accuracy_first10", "accuracy_last10", "learning_gain", "completion_rate", "final_mastery"]
    by = {c: {r["child_index"]: r for r in rows if r["condition"] == c} for c in runners}
    lines = [
        "# Learning outcomes by condition (Section IV-B / IV-F)",
        "",
        f"Mechanically generated by `research/run_learning_outcomes.py` — same setup as the simulation study (N={N_EVAL}, EVAL_SEED={EVAL_SEED}). "
        f"Learning gain = accuracy in the last {WINDOW} activities minus the first {WINDOW}. Completion = share of lesson activities not abandoned.",
        "",
        "| Condition | " + " | ".join(metrics) + " |",
        "|---|" + "---|" * len(metrics),
    ]
    for c in runners:
        lines.append(f"| {c} | " + " | ".join(f"{statistics.mean(r[m] for r in by[c].values()):.3f}" for m in metrics) + " |")
    lines += ["", "## Paired t-tests, AURA vs each baseline (Holm-adjusted within each metric)", "", "| Metric | vs | mean diff | t-test p | Holm-adjusted |", "|---|---|---|---|---|"]
    for m in ("accuracy", "learning_gain", "completion_rate"):
        tests = []
        for c in runners:
            if c == "AURA":
                continue
            a = [by["AURA"][i][m] for i in sorted(by["AURA"])]
            b = [by[c][i][m] for i in sorted(by["AURA"])]
            diff = statistics.mean(x - y for x, y in zip(a, b))
            p = stats.ttest_rel(a, b).pvalue if any(x != y for x, y in zip(a, b)) else 1.0
            tests.append([c, diff, p])
        order = sorted(range(len(tests)), key=lambda i: tests[i][2])
        running = 0.0
        for rank, i in enumerate(order):
            running = max(running, min(1.0, tests[i][2] * (len(tests) - rank)))
            tests[i].append(running)
        for c, diff, p, adj in tests:
            lines.append(f"| {m} | {c} | {diff:+.3f} | {p:.4f} | {adj:.4f}{' **significant**' if adj < 0.05 else ''} |")
    (RESULTS / "learning_outcomes.md").write_text("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
